# Generated by Django 4.1.5 on 2023-01-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('accounts', '0003_alter_profile_phone_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.club'),
        ),
    ]
