# Generated by Django 4.1.5 on 2023-01-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_order',
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizer_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizer_phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='propositions',
            name='organizer',
            field=models.ManyToManyField(blank=True, to='tournaments.organizer'),
        ),
        migrations.AddField(
            model_name='propositions',
            name='organizer_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.club'),
        ),
        migrations.AddField(
            model_name='propositions',
            name='start_fee',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propositions',
            name='tournament_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.function'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='category',
            field=models.ManyToManyField(blank=True, to='tournaments.category'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='discipline',
            field=models.ManyToManyField(blank=True, to='tournaments.discipline'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='league',
            field=models.ManyToManyField(blank=True, to='tournaments.league'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='tournaments.schedule'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.season'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='tournament_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.player'),
        ),
        migrations.AlterField(
            model_name='result',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='propositions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.propositions'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.season'),
        ),
    ]
