# Generated by Django 4.1.5 on 2023-01-21 09:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['club_name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['lastname']},
        ),
        migrations.AlterField(
            model_name='player',
            name='year_of_birth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), tournaments.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='result',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player'),
        ),
    ]
