# Generated by Django 4.1.5 on 2023-01-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['club_name']},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['organizer_lastname']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['lastname']},
        ),
        migrations.AlterModelOptions(
            name='propositions',
            options={'ordering': ['event_date']},
        ),
        migrations.AddField(
            model_name='player',
            name='player_is_girl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='year_of_birth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.player'),
        ),
        migrations.AlterUniqueTogether(
            name='organizer',
            unique_together={('organizer_name', 'organizer_lastname', 'organizer_mail', 'organizer_phone')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'lastname', 'year_of_birth')},
        ),
        migrations.AlterUniqueTogether(
            name='propositions',
            unique_together={('event_location', 'event_date', 'organizer_club')},
        ),
    ]
