# Generated by Django 4.1.5 on 2023-01-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositions',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='tournaments.organizer'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to='tournaments.organizer'),
        ),
        migrations.AlterField(
            model_name='propositions',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judge', to='tournaments.organizer'),
        ),
    ]
