# Generated by Django 4.1.5 on 2023-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['club_name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['lastname']},
        ),
        migrations.AddField(
            model_name='club',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
