# Generated by Django 4.1.2 on 2023-01-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_club_options_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.category'),
        ),
    ]
