# Generated by Django 4.1.5 on 2023-01-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_club_options_alter_player_options_club_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='license_validity',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='year_of_birth',
            field=models.IntegerField(),
        ),
    ]
